### ISSUE TITLE
Unable to login to docker using "ibmcloud cr login" command

### ISSUE THREAD

**Issue by jayzworld-github** [IBM/container-service-getting-started-wt#102]

**Comment by jpapejr** [comment]
Hi @jayzworld-github - seems like this would be better addressed with a support ticket to IBM Cloud. https://cloud.ibm.com/unifiedsupport/supportcenter will get you started..

**Comment by bhpratt** [comment]
Note - if you want to get around using `ibmcloud cr login` you can also just use `ibmcloud cr build` to build the image in the cloud and send to your private IBM Cloud registry.
