### ISSUE TITLE
Watson-Talk of the is not formatting JSON in the IBM BMX Container Tutorial

### ISSUE THREAD

**Issue by BanerjeeDeb** [IBM/container-service-getting-started-wt#11]
Though the tutorial claims in Lesson 3 that the JSON will be pretty formatted, it is not. Bluemix console seems to be down and I am unable to provide the URL.

Can this be addressed real soon? I am planning to use the sample in a live customer demo, where pretty printing is very important.

**Comment by colemanjackson** [comment]
@ramaboggarapu Could you take a look when you get a chance?

**Comment by jgarcows** [comment]
If you do a curl it is pretty formatted, but web browsers eat all the white space.  Try calling the url via curl or doing a view source on the web browser

**Comment by jgarcows** [comment]
I have a fix for this.  @BanerjeeDeb Can you confirm the following URL works for you (and I'll work on getting the fix merged)

http://169.47.249.155:30080/analyze/%22Today%20is%20a%20beautiful%20day%22

**Comment by BanerjeeDeb** [comment]
View source in browser does nothing! So is curl 
 
http://169.47.249.191:30080/analyze/%22Good%20day%22  produces something like the following which is not-so-elegant for a custimer demo. Is there any simple way to show the effect of escape characters?
 
"{\n  \"document_tone\": {\n    \"tone_categories\": [\n      {\n        \"tones\": [\n          {\n            \"score\": 0.016918,\n            \"tone_id\": \"anger\",\n            \"tone_name\": \"Anger\"\n          },\n          {\n            \"score\": 0.001096,\n            \"tone_id\": \"disgust\",\n            \"tone_name\": \"Disgust\"\n          },\n          {\n            \"score\": 0.019528,\n            \"tone_id\": \"fear\",\n            \"tone_name\": \"Fear\"\n          },\n          {\n            \"score\": 0.821089,\n            \"tone_id\": \"joy\",\n            \"tone_name\": \"Joy\"\n          },\n          {\n            \"score\": 0.046194,\n            \"tone_id\": \"sadness\",\n            \"tone_name\": \"Sadness\"\n          }\n        ],\n        \"category_id\": \"emotion_tone\",\n        \"category_name\": \"Emotion Tone\"\n      },\n      {\n        \"tones\": [\n          {\n            \"score\": 0,\n            \"tone_id\": \"analytical\",\n            \"tone_name\": \"Analytical\"\n          },\n          {\n            \"score\": 0,\n            \"tone_id\": \"confident\",\n            \"tone_name\": \"Confident\"\n          },\n          {\n            \"score\": 0,\n            \"tone_id\": \"tentative\",\n            \"tone_name\": \"Tentative\"\n          }\n        ],\n        \"category_id\": \"language_tone\",\n        \"category_name\": \"Language Tone\"\n      },\n      {\n        \"tones\": [\n          {\n            \"score\": 0.089535,\n            \"tone_id\": \"openness_big5\",\n            \"tone_name\": \"Openness\"\n          },\n          {\n            \"score\": 0.271937,\n            \"tone_id\": \"conscientiousness_big5\",\n            \"tone_name\": \"Conscientiousness\"\n          },\n          {\n            \"score\": 0.538943,\n            \"tone_id\": \"extraversion_big5\",\n            \"tone_name\": \"Extraversion\"\n          },\n          {\n            \"score\": 0.591919,\n            \"tone_id\": \"agreeableness_big5\",\n            \"tone_name\": \"Agreeableness\"\n          },\n          {\n            \"score\": 0.379002,\n            \"tone_id\": \"emotional_range_big5\",\n            \"tone_name\": \"Emotional Range\"\n          }\n        ],\n        \"category_id\": \"social_tone\",\n        \"category_name\": \"Social Tone\"\n      }\n    ]\n  }\n}"
Saludos,DebDebasish Banerjee, Ph. D.debasish@us.ibm.comHybrid Cloud Application Platform Technical Specialist, North America507.358.6486
 
 
----- Original message -----From: jgarcows <notifications@github.com>To: IBM/container-service-getting-started-wt <container-service-getting-started-wt@noreply.github.com>Cc: BanerjeeDeb <debasish@us.ibm.com>, Author <author@noreply.github.com>Subject: Re: [IBM/container-service-getting-started-wt] Watson-Talk of the is not formatting JSON in the IBM BMX Container Tutorial (#11)Date: Tue, May 9, 2017 11:49 AM 
If you do a curl it is pretty formatted, but web browsers eat all the white space. Try calling the url via curl or doing a view source on the web browser

**Comment by BanerjeeDeb** [comment]
Yes. It is working now in your URL. When can I expect to receive the fix?
 
Saludos,DebDebasish Banerjee, Ph. D.debasish@us.ibm.comHybrid Cloud Application Platform Technical Specialist, North America507.358.6486
 
 
----- Original message -----From: jgarcows <notifications@github.com>To: IBM/container-service-getting-started-wt <container-service-getting-started-wt@noreply.github.com>Cc: BanerjeeDeb <debasish@us.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [IBM/container-service-getting-started-wt] Watson-Talk of the is not formatting JSON in the IBM BMX Container Tutorial (#11)Date: Tue, May 9, 2017 12:00 PM 
I have a fix for this. @BanerjeeDeb Can you confirm the following URL works for you (and I'll work on getting the fix merged)
http://169.47.249.155:30080/analyze/%22Today%20is%20a%20beautiful%20day%22

**Comment by jgarcows** [comment]
@BanerjeeDeb Fix is delivered.  Let me know if there are any problems.

**Comment by BanerjeeDeb** [comment]
I did a git clone, rebuild all the images after removing them from BMX and still the things are the same. Was the fix tested?
Saludos,DebDebasish Banerjee, Ph. D.debasish@us.ibm.comHybrid Cloud Application Platform Technical Specialist, North America507.358.6486
 
 
----- Original message -----From: jgarcows <notifications@github.com>To: IBM/container-service-getting-started-wt <container-service-getting-started-wt@noreply.github.com>Cc: BanerjeeDeb <debasish@us.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [IBM/container-service-getting-started-wt] Watson-Talk of the is not formatting JSON in the IBM BMX Container Tutorial (#11)Date: Tue, May 9, 2017 12:13 PM 
Closed #11.

**Comment by jgarcows** [comment]
Yes the fix was tested, the URL I pasted was running on the fixed code.  Try deleting your deployment/services and creating it again with the yml file.  

I believe the yml was set to only pull images if they weren't in the deployment.  You could also try to tag the images with something else instead of latest and update the deployments to use those tags.

**Comment by BanerjeeDeb** [comment]
Hi,
 
Yes my cluster was using the cached image. My mistake and apologies.
 
I changed the image pull policy in the yml file and it worked this afternoon. I would suggest for the tutorials, we should use Always by default to avoid similar mistakes.
Saludos,DebDebasish Banerjee, Ph. D.debasish@us.ibm.comHybrid Cloud Application Platform Technical Specialist, North America507.358.6486
 
 
----- Original message -----From: jgarcows <notifications@github.com>To: IBM/container-service-getting-started-wt <container-service-getting-started-wt@noreply.github.com>Cc: BanerjeeDeb <debasish@us.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [IBM/container-service-getting-started-wt] Watson-Talk of the is not formatting JSON in the IBM BMX Container Tutorial (#11)Date: Tue, May 9, 2017 8:58 PM 
Yes the fix was tested, the URL I pasted was running on the fixed code. Try deleting your deployment/services and creating it again with the yml file.
I believe the yml was set to only pull images if they weren't in the deployment. You could also try to tag the images with something else instead of latest and update the deployments to use those tags.
