### ISSUE TITLE
Lab 1:  ibmcloud 'cr' is not a registered command. See 'ibmcloud help'.

### ISSUE THREAD

**Issue by ghost** [IBM/container-service-getting-started-wt#110]
When attempting to walk through the documentation on Lab 1, we encounter an issue where when running the following:

**Error:**
[docker@linuxmachine ~]$ ibmcloud cr namespace-add my-test-namespace
FAILED
'cr' is not a registered command. See 'ibmcloud help'.

**IBM Cloud Version:**
VERSION:
0.19.0+94101c85-2019-09-23T03:46:57+00:00

Thanks.

**Comment by bhpratt** [comment]
Review lab 0 for the cli and plugin installations: https://github.com/IBM/container-service-getting-started-wt/blob/master/Lab%200/README.md

**Comment by hintcnuie** [comment]
ibmcloud cr is an plugin for the IBMCloud CLI,  you can install using :

`ibmcloud plugin install container-registry -r 'IBM Cloud'`

Reference:
https://cloud.ibm.com/kubernetes/registry/main/start
