### ISSUE TITLE
Failing to deploy app hello-world (Lab 1)

### ISSUE THREAD

**Issue by carloshgs** [IBM/container-service-getting-started-wt#111]
After running the command: 
kubectl run hello-world --image=us.icr.io/<namespace>/hello-world
it returns the following error:
error: failed to discover supported resources: Get http://localhost:8080/apis/apps/v1?timeout=32s: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.

**Comment by jpapejr** [comment]
Export your cluster config first  ‘ibmcloud ks cluster config —cluster xxx’

**Comment by carloshgs** [comment]
Thanks jpapejr for the reply! I did export the config before, but the deploy doesn´t work. The Cluster and the Worker have status normal and ready.

**Comment by jpapejr** [comment]
It’s clearly not exported if kubectl is trying to talk to localhost:8080.

**Comment by hintcnuie** [comment]
yes, first cmd:
` ibmcloud ks clusters`
<img width="1047" alt="Screen Shot 2020-01-13 at 6 03 31 PM" src="https://user-images.githubusercontent.com/4081542/72247110-2cba6f80-362f-11ea-9b32-19dadffbeb25.png">

and copy the clusterID,

 the second command,
  `ibmcloud ks  cluster config --cluster <clusterID>`
<img width="1047" alt="Screen Shot 2020-01-13 at 6 06 49 PM" src="https://user-images.githubusercontent.com/4081542/72247278-81f68100-362f-11ea-81d9-e3a825ad93dc.png">

 then export the output from previous command.

And another command is available:
`export IKS_BETA_VERSION=1`
