### ISSUE TITLE
 kubectl run --generator=deployment/apps.v1 is DEPRECATED issue

### ISSUE THREAD

**Issue by hintcnuie** [IBM/container-service-getting-started-wt#113]
In lab1, when running the below command:
`kubectl run hello-world  --image=us.icr.io/<namespace>/hello-world`

it pops up a warning message saying kubectl run --generator=deployment/apps.v1 is deprecated,

see 

<img width="1076" alt="Screen Shot 2020-01-13 at 6 01 32 PM" src="https://user-images.githubusercontent.com/4081542/72247705-6fc91280-3630-11ea-8850-f0f532bc85b2.png">

**Comment by bhpratt** [comment]
Pr submitted for fix. Thanks https://github.com/IBM/container-service-getting-started-wt/pull/124
