### ISSUE TITLE
deployment "hello-world" scaled is mixed with the command line

### ISSUE THREAD

**Issue by hintcnuie** [IBM/container-service-getting-started-wt#114]
in the first step, it says:

1. `kubectl` provides a `scale` subcommand to change the size of an
   existing deployment. Let's us it to go from our single running
   instance to 10 instances.
   
   ``` console 
   $ kubectl scale --replicas=10 deployment hello-world
   deployment "hello-world" scaled
   ```

but  it's better to separate the result and command,  think about this. it's more clear for the script to be executed and avoid misunderstanding.

``` console
$ kubectl scale --replica=10 deployment hello-world

```

**Comment by jgarcows** [comment]
Fixed and merged.
