### ISSUE TITLE
Error: deployments.apps <namespace> not found

### ISSUE THREAD

**Issue by koyurin** [IBM/container-service-getting-started-wt#119]
The instruction below would better to be corrected.

Lab1 2-2
Start by running your image as a deployment:
kubectl run hello-world --image=us.icr.io/<namespace>/hello-world:1

When I used the run command, only pod was created but deployment was not and at the Lab1 2-3, I encountered "Error: deployments.apps <namespace> not found"

Instead of using run command, It seems better to use create deployment command, such as
kubectl create deployment  hello-world --image=us.icr.io/<namespace>/hello-world:1

**Comment by bhpratt** [comment]
PR submitted for fix. Thanks https://github.com/IBM/container-service-getting-started-wt/pull/124
