### ISSUE TITLE
Lab 1 - Error from server (NotFound): deployments.apps "hello-world" not found

### ISSUE THREAD

**Issue by AndersonIsHere** [IBM/container-service-getting-started-wt#120]
Hi,

At Lab 1, step 3:

kubectl expose deployment/hello-world --type="NodePort" --port=8080

I received this message:

Error from server (NotFound): deployments.apps "hello-world" not found

To fix it, at Lab 1 at step 2, I  changed from

run hello-world --image=us.icr.io/<my_namespace>/hello-world:1

to

kubectl create deployment hello-world --image=us.icr.io/<my_namespace>/hello-world:1

It solved some others problems along Lab 1 and Lab 2 too.

**Comment by bhpratt** [comment]
PR submitted for fix. Thanks https://github.com/IBM/container-service-getting-started-wt/pull/124

**Comment by mythreyi1905** [comment]
> Hi,
> 
> At Lab 1, step 3:
> 
> kubectl expose deployment/hello-world --type="NodePort" --port=8080
> 
> I received this message:
> 
> Error from server (NotFound): deployments.apps "hello-world" not found
> 
> To fix it, at Lab 1 at step 2, I changed from
> 
> run hello-world --image=us.icr.io/<my_namespace>/hello-world:1
> 
> to
> 
> kubectl create deployment hello-world --image=us.icr.io/<my_namespace>/hello-world:1
> 
> It solved some others problems along Lab 1 and Lab 2 too.

This helps. kubectl run only creates pods and services. Deployments do not get created automatically.
