### ISSUE TITLE
Kubernetes Lab 1 : -bash: docker: command not found  ( using cloudshell )

### ISSUE THREAD

**Issue by shubhrojyotide** [IBM/container-service-getting-started-wt#122]
From Kuberenetes LAB 1 :
https://courses.cognitiveclass.ai/courses/course-v1:CognitiveClass+CO0201EN+v1/courseware/754094ea513a42f39ec84d99cae78249/f1cc315d40b74e1aa6ec1cd2a3c1f985/

Create a namespace in IBM Cloud Container Registry where you can store your images:
ibmcloud cr namespace-add <my_namespace>   -------------------->  I created k8-ns-shubhro

Build the example Docker image:
docker build --tag us.icr.io/<my_namespace>/hello-world . --------------->  This is failing 

shubhrojyoti_de@cloudshell:~$ docker build --tag us.icr.io/k8-ns-shubhro/hello-world
-bash: docker: command not found

Please help on this.

**Comment by MarquinheGit** [comment]
Hi 
I used this:
ibmcloud cr build --tag us.icr.io/<my_namespace>/hello-world:1 .

be aware the "dot" at the end

> From Kuberenetes LAB 1 :
> https://courses.cognitiveclass.ai/courses/course-v1:CognitiveClass+CO0201EN+v1/courseware/754094ea513a42f39ec84d99cae78249/f1cc315d40b74e1aa6ec1cd2a3c1f985/
> 
> Create a namespace in IBM Cloud Container Registry where you can store your images:
> ibmcloud cr namespace-add <my_namespace> --------------------> I created k8-ns-shubhro
> 
> Build the example Docker image:
> docker build --tag us.icr.io/<my_namespace>/hello-world . ---------------> This is failing
> 
> shubhrojyoti_de@cloudshell:~$ docker build --tag us.icr.io/k8-ns-shubhro/hello-world
> -bash: docker: command not found
> 
> Please help on this.

**Comment by bhpratt** [comment]
Make sure you have docker installed locally. That error is saying it can't find docker.

Or use @MarquinheGit's `ibmcloud cr build` suggestion. Which is the preferred method and the one used in this repo's instructions.
