### ISSUE TITLE
Lab 2: healthz not working

### ISSUE THREAD

**Issue by vwilburn** [IBM/container-service-getting-started-wt#41]
In the Health Check section, I didn't get the same errors as described. Also, I couldn't get the healthz URL to work with this error message: 
`Cannot GET /healthz `

So you'll see [my PR](https://github.com/IBM/container-service-getting-started-wt/pull/43) removed the specific messages. I did see the pods appropriately restarting in the Kube dashboard.

**Comment by jkomg** [comment]
Is this fixed now that we've added the Stage directories?

**Comment by vwilburn** [comment]
No, I couldn't get that section to work with or without the Stage directories. Could you?

**Comment by vwilburn** [comment]
Because VW genercized the content, I think we can call this one done.
