### ISSUE TITLE
Lab 2 missing files

### ISSUE THREAD

**Issue by vwilburn** [IBM/container-service-getting-started-wt#44]
Lab 2 needs the Stage1, Stage2, and Stage 3 directories from this repo:
https://github.com/Osthanes/container-service-getting-started-wt

Maybe you could get away with omitting Stage1 and Stage3, but I didn't test it that way.

**Comment by jkomg** [comment]
@vwilburn I'll add these in. I'm not sure how I got through it without these...

**Comment by jkomg** [comment]
@vwilburn I don't actually see what files are necessary. It looks like Lab2 is fine. Can you clarify which parts are giving you issues?

**Comment by vwilburn** [comment]
@kennjason My testing got stuck when I came to this instruction:
_"To try the HTTP liveness check, first, cd into the Stage2 directory, then create and push the sigex-demo-health image to the IBM Cloud Container Registry:"_

The repo path doesn't have a Stage2 directory:
https://github.com/IBM/container-service-getting-started-wt/tree/master/Lab%202

But I did find a Stage2 directory in the forked repo:
https://github.com/Osthanes/container-service-getting-started-wt/tree/master/Stage2

I hope the above makes sense. If not, let me know.

**Comment by jkomg** [comment]
See https://github.com/IBM/container-service-getting-started-wt/pull/45; added

**Comment by jkomg** [comment]
This is set.
