### ISSUE TITLE
Lab 1 cluster provision cmd doesn't work

### ISSUE THREAD

**Issue by linsun** [IBM/container-service-getting-started-wt#58]
I think that cmd used to work when we only support us-south... but as you can see it failed for me.  I think I'm pointed to us-east by default now.  we need to tweak this cmd either by having user point to us-south first.

$ bx cs cluster-create --name  test
Creating cluster...
The machine-type flag was not specified. So a lite cluster with default parameters will be created. To customize the parameters, create a standard cluster and include all required flags.
FAILED

Free clusters cannot be created in this region. Create a standard cluster.   (E0141)
Incident ID: e5ca7fc2-8c03-44e7-babd-2ceb2e9c9525

**Comment by bhpratt** [comment]
I go back and forth on this one. The command works in every case (I believe), unless you have done the following:
1) logged into the ng region w/the cluster service
2) and switched regions from us south

Most beginners won't have done the above (particularly #2). And I'd prefer not to add additional commands about switching regions if we don't need to. That being said, if we do think this will trip up users, maybe we could add a blurb about creating the cluster in us south.

**Comment by bhpratt** [comment]
w/some of the regional/global api changes, I believe this is no longer an issue
