### ISSUE TITLE
Lab 6 - we need to switch to another log and metrics solution

### ISSUE THREAD

**Issue by linsun** [IBM/container-service-getting-started-wt#62]
We don't have any partnership with the current solution mentioned in there, e.g.  Instana

Nilesh suggested to use sematext from @chris Rosen's blog https://www.ibm.com/blogs/bluemix/2017/09/monitoring-logging-ibm-bluemix-container-service-sematext/

Chris has confirmed that is the best choice today for free cluster.  I have also confirmed with armada dev that it is not trivial to enable log and metrics service for free cluster.

**Comment by jkomg** [comment]
Per our last conversation, I've removed lab 6 from the repo. 

#65

**Comment by linsun** [comment]
Thanks Jason!

**Comment by MHBauer** [comment]
#65 merged
