### ISSUE TITLE
LAB 6 URL issue

### ISSUE THREAD

**Issue by briansay** [IBM/container-service-getting-started-wt#82]
Lab 6, when i click the URL it gives a 404 error

**Comment by bhpratt** [comment]
Can you copy/paste the URL that you clicked on? And are you referring to this Lab? https://github.com/IBM/container-service-getting-started-wt/tree/master/Lab%205

**Comment by briansay** [comment]
Hey,

From this link https://github.com/IBM/container-service-getting-started-wt
is the following:
[image: image.png]

When I select LAB6 it sends me to
https://github.com/IBM/container-service-getting-started-wt/tree/master/Lab%206
which gives a 404 issue


Brian Say
Mobile: 07769557199
Email: brian.say91@gmail.com
<https://uk.linkedin.com/pub/brian-say/8a/265/444>

**Comment by bhpratt** [comment]
Ah, I see, thanks. It looks like that lab has been removed (or perhaps is in development). I'll remove the link. Thanks for raising the issue.

**Comment by jgarcows** [comment]
Merged.  https://github.com/IBM/container-service-getting-started-wt/pull/83
