### ISSUE TITLE
change bx to ibmcloud

### ISSUE THREAD

**Issue by ebasso** [IBM/container-service-getting-started-wt#84]
I started to do this course and see that bx command is deprecated.

As of May 2018 the IBM Cloud CLI commands have changed from bluemix and bx to ibmcloud. However you can still use the bluemix and bx CLI commands until they are removed at a later date.
See at: https://console.bluemix.net/docs/cli/reference/ibmcloud/bx_cli.html#ibmcloud_cli

**Comment by bhpratt** [comment]
PR https://github.com/IBM/container-service-getting-started-wt/pull/97
