### ISSUE TITLE
remove full docker requirement needed get image in repo

### ISSUE THREAD

**Issue by ibmrcruicks** [IBM/container-service-getting-started-wt#95]

**Comment by ibmrcruicks** [comment]
to get this lab to work, user needs to have full docker service running locally
this means mixing 
1. ibmcloud cr
1. ibmcloud cs
1. docker
1. kubectl

replacing the docker build+push steps with `ibmcloud cr build` would reduce complexity and context switching. This would also allow users to install a docker cli rather than the full service - a more attractive option for developers new to K*S, Docker and IBM Cloud

**Comment by bhpratt** [comment]
agreed. addressed with PR: https://github.com/IBM/container-service-getting-started-wt/pull/107
